/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bihan.exportmanager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ExportManagerField service. Represents a row in the &quot;EM_ExportManagerField&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bihan.exportmanager.model.impl.ExportManagerFieldModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bihan.exportmanager.model.impl.ExportManagerFieldImpl}.
 * </p>
 *
 * @author sebastienbihan
 * @see ExportManagerField
 * @see com.bihan.exportmanager.model.impl.ExportManagerFieldImpl
 * @see com.bihan.exportmanager.model.impl.ExportManagerFieldModelImpl
 * @generated
 */
public interface ExportManagerFieldModel extends BaseModel<ExportManagerField> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a export manager field model instance should use the {@link ExportManagerField} interface instead.
	 */

	/**
	 * Returns the primary key of this export manager field.
	 *
	 * @return the primary key of this export manager field
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this export manager field.
	 *
	 * @param primaryKey the primary key of this export manager field
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the export manager field ID of this export manager field.
	 *
	 * @return the export manager field ID of this export manager field
	 */
	public long getExportManagerFieldId();

	/**
	 * Sets the export manager field ID of this export manager field.
	 *
	 * @param exportManagerFieldId the export manager field ID of this export manager field
	 */
	public void setExportManagerFieldId(long exportManagerFieldId);

	/**
	 * Returns the export manager ID of this export manager field.
	 *
	 * @return the export manager ID of this export manager field
	 */
	public long getExportManagerId();

	/**
	 * Sets the export manager ID of this export manager field.
	 *
	 * @param exportManagerId the export manager ID of this export manager field
	 */
	public void setExportManagerId(long exportManagerId);

	/**
	 * Returns the field name of this export manager field.
	 *
	 * @return the field name of this export manager field
	 */
	@AutoEscape
	public String getFieldName();

	/**
	 * Sets the field name of this export manager field.
	 *
	 * @param fieldName the field name of this export manager field
	 */
	public void setFieldName(String fieldName);

	/**
	 * Returns the field display name of this export manager field.
	 *
	 * @return the field display name of this export manager field
	 */
	@AutoEscape
	public String getFieldDisplayName();

	/**
	 * Sets the field display name of this export manager field.
	 *
	 * @param fieldDisplayName the field display name of this export manager field
	 */
	public void setFieldDisplayName(String fieldDisplayName);

	/**
	 * Returns the position of this export manager field.
	 *
	 * @return the position of this export manager field
	 */
	public int getPosition();

	/**
	 * Sets the position of this export manager field.
	 *
	 * @param position the position of this export manager field
	 */
	public void setPosition(int position);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ExportManagerField exportManagerField);

	public int hashCode();

	public CacheModel<ExportManagerField> toCacheModel();

	public ExportManagerField toEscapedModel();

	public ExportManagerField toUnescapedModel();

	public String toString();

	public String toXmlString();
}