/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bihan.exportmanager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ExportManagerFields service. Represents a row in the &quot;EM_ExportManagerFields&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bihan.exportmanager.model.impl.ExportManagerFieldsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bihan.exportmanager.model.impl.ExportManagerFieldsImpl}.
 * </p>
 *
 * @author sebastienbihan
 * @see ExportManagerFields
 * @see com.bihan.exportmanager.model.impl.ExportManagerFieldsImpl
 * @see com.bihan.exportmanager.model.impl.ExportManagerFieldsModelImpl
 * @generated
 */
public interface ExportManagerFieldsModel extends BaseModel<ExportManagerFields> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a export manager fields model instance should use the {@link ExportManagerFields} interface instead.
	 */

	/**
	 * Returns the primary key of this export manager fields.
	 *
	 * @return the primary key of this export manager fields
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this export manager fields.
	 *
	 * @param primaryKey the primary key of this export manager fields
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the export manager fields ID of this export manager fields.
	 *
	 * @return the export manager fields ID of this export manager fields
	 */
	public long getExportManagerFieldsId();

	/**
	 * Sets the export manager fields ID of this export manager fields.
	 *
	 * @param exportManagerFieldsId the export manager fields ID of this export manager fields
	 */
	public void setExportManagerFieldsId(long exportManagerFieldsId);

	/**
	 * Returns the export manager ID of this export manager fields.
	 *
	 * @return the export manager ID of this export manager fields
	 */
	public long getExportManagerId();

	/**
	 * Sets the export manager ID of this export manager fields.
	 *
	 * @param exportManagerId the export manager ID of this export manager fields
	 */
	public void setExportManagerId(long exportManagerId);

	/**
	 * Returns the field name of this export manager fields.
	 *
	 * @return the field name of this export manager fields
	 */
	@AutoEscape
	public String getFieldName();

	/**
	 * Sets the field name of this export manager fields.
	 *
	 * @param fieldName the field name of this export manager fields
	 */
	public void setFieldName(String fieldName);

	/**
	 * Returns the field label of this export manager fields.
	 *
	 * @return the field label of this export manager fields
	 */
	@AutoEscape
	public String getFieldLabel();

	/**
	 * Sets the field label of this export manager fields.
	 *
	 * @param fieldLabel the field label of this export manager fields
	 */
	public void setFieldLabel(String fieldLabel);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ExportManagerFields exportManagerFields);

	public int hashCode();

	public CacheModel<ExportManagerFields> toCacheModel();

	public ExportManagerFields toEscapedModel();

	public ExportManagerFields toUnescapedModel();

	public String toString();

	public String toXmlString();
}